### ISSUE TITLE
How to generate SSN, email, and phone Numbers tied to clients

### ISSUE THREAD

**Issue by ngshya** [voutilad/PaySim#5]
Hi there! I have run successfully the first simulation with 

> java -jar ./target/paysim-2.4.0.jar

but cannot find the output file containing emails, phone numbers, etc. Should I change any parameter in the properties file? 

Thank you in advance for your kind help!

**Comment by voutilad** [comment]
The identifier data is currently accessible via a reference to the current `PaySimState` implementation. I haven't implemented anything in the `main` methods in this project, but here's an example from a downstream project that uses this library: https://github.com/voutilad/paysim-demo/blob/882250ad90b8c87e2bcdfe3c9343d5abb9326c90/src/main/java/io/sisu/paysim/App.java#L125-L134

The `PaySimState` implementations have access to the actors via `getClients()`, `getMerchants()`, `getFraudsters()` and the `getBanks()` getters. Each actor implements the `Identifiable` interface that provides a getter for the `Identity` implementation they are given by the simulation.

**Comment by ngshya** [comment]
Thanks @voutilad!
